<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net48</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <DisableFody>true</DisableFody>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <Import Project="../TestLangFeatures.targets" />

  <ItemGroup>
    <PackageReference Include="FodyHelpers" Version="$(FodyVersion)" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="System.Reflection.Metadata" Version="10.0.10" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InlineIL.Fody\InlineIL.Fody.csproj" />
    <ProjectReference Include="..\InlineIL.Tests.Common\InlineIL.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InlineILTestProject Include="..\InlineIL.Tests.AssemblyToProcess\InlineIL.Tests.AssemblyToProcess.csproj" />
    <InlineILTestProject Include="..\InlineIL.Tests.InvalidAssemblyToProcess\InlineIL.Tests.InvalidAssemblyToProcess.csproj" />
    <InlineILTestProject Include="..\InlineIL.Tests.StandardAssemblyToProcess\InlineIL.Tests.StandardAssemblyToProcess.csproj" Aliases="standard" />
    <InlineILTestProject Include="..\InlineIL.Tests.UnverifiableAssemblyToProcess\InlineIL.Tests.UnverifiableAssemblyToProcess.csproj" />

    <InlineILTestProject Update="@(InlineILTestProject)" Visible="false" />
    <ProjectReference Include="@(InlineILTestProject)" ReferenceOutputAssembly="false" OutputItemType="InlineILTestProjectAssembly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InlineIL.Tests.InjectedAssembly\InlineIL.Tests.InjectedAssembly.csproj" ReferenceOutputAssembly="false" OutputItemType="None" CopyToOutputDirectory="PreserveNewest" TargetPath="InlineIL.Tests.InjectedAssembly.dll" />
    <ProjectReference Include="..\InlineIL.Tests.InjectedAssembly.Alternative\InlineIL.Tests.InjectedAssembly.Alternative.csproj" ReferenceOutputAssembly="false" OutputItemType="None" CopyToOutputDirectory="PreserveNewest" TargetPath="InlineIL.Tests.InjectedAssembly.Alternative.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="InlineILAddTestAssemblies"
          AfterTargets="ResolveProjectReferences"
          BeforeTargets="GetCopyToOutputDirectoryItems">
    <ItemGroup>
      <ContentWithTargetPath Include="@(InlineILTestProjectAssembly)"
                             CopyToOutputDirectory="PreserveNewest"
                             TargetPath="TestAssemblies/%(Filename)%(Extension)" />

      <ContentWithTargetPath Include="@(InlineILTestProjectAssembly->'%(RootDir)%(Directory)%(Filename).pdb')"
                             CopyToOutputDirectory="PreserveNewest"
                             TargetPath="TestAssemblies/%(Filename).pdb" />

      <ContentWithTargetPath Include="@(InlineILTestProjectAssembly->'%(RootDir)%(Directory)%(Filename).refs.txt')"
                             CopyToOutputDirectory="PreserveNewest"
                             TargetPath="TestAssemblies/%(Filename).refs.txt" />
    </ItemGroup>
  </Target>

</Project>
